package enums;

public enum ValidacaoArquivoEnum {

	SUCESSO, PREENCHIMENTO_OBRIGATORIO_DIRETORIO, PREENCHIMENTO_OBRIGATORIO_METODO_DEUS,
	PREENCHIMENTO_OBRIGATORIO_CLASSE_DEUS, DIRETORIO_NAO_ENCONTRADO, TIPO_ARQUIVO_INCORRETO, ARQUIVO_NAO_SUPORTADO,
	ERRO_CONVERSAO_DIRETORIO, PREENCHIMENTO_INCORRETO_CLASSE_DEUS, PREENCHIMENTO_INCORRETO_METODO_DEUS,
	ARQUIVO_ANALISADO, MESSAGE_SELECIONE_GRAFICO;

}
